name-template: 'Draft'
template: |
  # What's Changed

  $CHANGES

categories:
  - title: '🚀 Features'
    label: 'enhancement'
  - title: '🐛 Bug Fixes'
    label: 'bug'
  - title: '📝 Documentation'
    label: 'documentation'
    collapse-after: 5

exclude-labels:
  - 'skip-changelog'
