name: Pull Request Style Check

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled
      - edited
    branches:
      - develop


jobs:
  check_cc_labels:
    name: check conventional commits labels
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-required-labels@v5
        with:
          mode: minimum
          count: 1
          labels: |
            bug
            documentation
            enhancement
            skip-changelog
