name: Semantic Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install poetry
        uses: Gr1N/setup-poetry@v8

      - name: Cache poetry dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}

      - name: Install dependencies
        run: poetry install

      - name: Python Semantic Release
        uses: relekang/python-semantic-release@v7
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository_username: __token__
          repository_password: ${{ secrets.TESTPYPI_TOKEN }}
    #   - name: Python Semantic Release
    #     run: |
    #       git config --global user.name "github-actions"
    #       git config --global user.email "action@github.com"

    #       poetry run semantic-release publish -D commit_author="github-actions <action@github.com>"
    #     env:
    #       GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    #       PYPI_TOKEN: ${{secrets.TESTPYPI_TOKEN}}
